// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: chatup.proto

#include "chatup.pb.h"
#include "chatup.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace chatup {

static const char* ChatupApi_method_names[] = {
  "/chatup.ChatupApi/Send",
};

std::unique_ptr< ChatupApi::Stub> ChatupApi::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ChatupApi::Stub> stub(new ChatupApi::Stub(channel, options));
  return stub;
}

ChatupApi::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Send_(ChatupApi_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ChatupApi::Stub::Send(::grpc::ClientContext* context, const ::chatup::Message& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::chatup::Message, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Send_, context, request, response);
}

void ChatupApi::Stub::async::Send(::grpc::ClientContext* context, const ::chatup::Message* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::chatup::Message, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Send_, context, request, response, std::move(f));
}

void ChatupApi::Stub::async::Send(::grpc::ClientContext* context, const ::chatup::Message* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Send_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* ChatupApi::Stub::PrepareAsyncSendRaw(::grpc::ClientContext* context, const ::chatup::Message& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::chatup::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Send_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* ChatupApi::Stub::AsyncSendRaw(::grpc::ClientContext* context, const ::chatup::Message& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendRaw(context, request, cq);
  result->StartCall();
  return result;
}

ChatupApi::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatupApi_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatupApi::Service, ::chatup::Message, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatupApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chatup::Message* req,
             ::google::protobuf::Empty* resp) {
               return service->Send(ctx, req, resp);
             }, this)));
}

ChatupApi::Service::~Service() {
}

::grpc::Status ChatupApi::Service::Send(::grpc::ServerContext* context, const ::chatup::Message* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace chatup

